# ------ root_path/dataset_name ------
root_path: 'data'

seed: 3407
## The seed 3407 comes from the paper:
##    ''Torch.manual_seed(3407) is all you need: 
##      On the influence of random seeds in deep learning architectures for computer vision''

# ------ Hyperparamters ------
search_hp: True

search_scale: [7, 7, 0.5]
search_step: [200, 20, 5]

init_beta: 1
init_alpha: 2
init_gamma: 0.1

eps: 0.001
feat_num: 500

w_training_free: [0.7, 0.3]
w_training: [0.2, 0.8]

# ------ Basic Config ------
dataset: 'imagenet'
backbone: 'RN50'

lr: 0.0001
augment_epoch: 10
train_epoch: 20